print("Các lỗi trong lập trình  và cách bắt lỗi trong Python: ")
print("1. Lỗi cú pháp (Syntax Error):")
print("Lỗi cú pháp xảy ra khi bạn viết mã không tuân theo quy tắc ngữ pháp của ngôn ngữ lập trình. Ví dụ:")
print("Ví dụ: ")
print("if x > 10 print('x lớn hơn 10')  # Thiếu dấu hai chấm (:) sau điều kiện if")
print("Cách khắc phục: Thêm dấu hai chấm (:) sau điều kiện if.")
print("\n2. Lỗi vi phạm nguyên tắc sử dụng biến:")
print("Lỗi này xảy ra khi bạn sử dụng biến mà chưa khai báo hoặc gán giá trị cho nó. Ví dụ:")
print("Ví dụ: ")
print("print(y)  # y chưa được khai báo trước đó")
print("Cách khắc phục: Khai báo và gán giá trị cho biến trước khi sử dụng nó.")
print("\n3. Lỗi thực thi:")
print("Lỗi thực thi xảy ra khi chương trình gặp sự cố trong quá trình chạy, dẫn đến việc chương trình bị dừng đột ngột. Ví dụ:")
print("Cách khắc phục: Sử dụng cấu trúc try-except để bắt lỗi và xử lý chúng một cách hợp lý. ")
